### ISSUE TITLE
Any demo or readme? 

### ISSUE THREAD

**Issue by KarelWintersky** [SignpostMarv/daft-router#10]
Wanted!

**Comment by SignpostMarv** [comment]
none *public* at present, beyond the [Implementation Test](https://github.com/daft-framework/daft-router/blob/master/Tests/ImplementationTest.php)

**Comment by SignpostMarv** [comment]
The basic gist is that middleware can filter what routes they're included in at compile time such that one does not need to wait until runtime / instantiation to figure out if a given middleware or interceptor needs to run.

daft-router also supports a class of middleware referred to as an [interceptor](https://github.com/daft-framework/daft-router/blob/master/src/DaftRequestInterceptor.php), which is effectively a piece of middleware whose optional reponse object is intended to be used instead of executing the route (i.e. performing access control via an interceptor rather than duplicating a check in many routes).

[daft-framework includes a console command](https://github.com/daft-framework/daft-framework/blob/4516b84f0114c2d3fdfe73e75deaeec3f7771ecf/src/Symfony/Console/Command/FastRouteCacheCommand.php) that accepts a bunch of [sources](https://github.com/daft-framework/daft-router/blob/master/src/DaftSource.php) and generates a nikic/fast-route cache ready for use.

since there's no readme or public demo at present, you're probably best off asking specific questions & I'll endeavour to answer them :)

**Comment by KarelWintersky** [comment]
I am looking for simple, fast and good-documented router, that can do something like this:

```
AppRouter::init(AppLogger::scope('routing'));

AppRouter::setDefaultNamespace('\SteamPunkEngine\Mobile');
AppRouter::get('/', 'Index@view_frontpage');
AppRouter::get('/auth/', 'Auth@view_form_login');
AppRouter::post('/auth/', 'Auth@callback_login');
AppRouter::get('/pages/{id}/', 'Page@view_page_by_id'); 
AppRouter::get('/ajax/articles:cnews:get:more/{page}', 'Articles\CNews@ajax_load_more');
AppRouter::get('/clinics/{id:\d+}/', 'Providers\Clinics@view_item'); 
AppRouter::get('/clinics/{id:\d+}/replies/{rid:\d+}', 'Providers\Clinics@view_item_replies_item');
AppRouter::get('/pharmacies/{id:\d+}/', 'Providers\Pharmacy@view_item');
AppRouter::get('/pharmacies/{id:\d+}/map/', 'Providers\Pharmacy@view_item_on_map');

AppRouter::group([
'prefix' => '/authnew/',
'middleware' => Middleware::class,
'namespace' => 'AuthNamespace'
], function(){
.... with other prefix, middleware or namespace
});

AppRouter::dispatch();
```

without Laravel, Lumen, Symphony, Zend and other HEAVY frameworks

**Comment by SignpostMarv** [comment]
ah, well while this router *does* use symfony components, it doesn't require the entire framework.

it does not however, support grouping- this has to be implemented elsewhere.

routes are based around classes, not class methods.

so without doing arg-based conditional route handling, you'd end up with something like this:

```php
class AppSource implements DaftSource {
    public static function DaftRouterRouteAndMiddlewareSources() : array {
        return [
            Index::class,
            Auth::class,
            Page::class,
            Article::class,
            Clinic::class,
            ClinicReplies::class,
            Pharmacy::class,
            PharmacyMap::class,
        ];
    }
}
```

then you'd do this (borrowed from [daft-framework](https://github.com/daft-framework/daft-framework/blob/cde1259c904d8c18332ddf3f4ba3747673c3b07e/src/HttpHandler.php#L65)):
```php
function handle(Request $request, string $url_prefix) : Response {
    $dispatcher = Compiler::ObtainDispatcher(
        [
            'cacheFile' => '/path/to/cache-file.php',
        ],
        AppSource::class,
        SomeOtherSourceHandlingMiddleware::class
    );

    return $dispatcher->handle($request, $url_prefix);
}
```

**Comment by SignpostMarv** [comment]
putting together a working example currently.

**Comment by SignpostMarv** [comment]
[here is a working example](https://github.com/daft-framework/Daft-Router-Example), no examples of middleware/interceptors as yet, though.

**Comment by KarelWintersky** [comment]
It's not a simple routing library :( 

your implementation is too overloaded
